---
- name: Install python3-docker (Docker SDK for Python)
  apt:
    name: python3-docker
    update_cache: "{{ apt_update_cache | default('True') }}"

- name: "Login to private registry at {{ item.registry }} and force re-authorization"
  docker_login:
    registry: "{{ item.registry }}"
    username: "{{ item.user }}"
    password: "{{ item.passwd }}"
    reauthorize: yes
  no_log: True
  with_items: "{{ docker_registry_client_credentials | default([]) }}"